#!/usr/bin/env python3
"""Walk every phase folder, count checkboxes in each phase's index.md, and
emit docs/progress.md with a completion table.

A checked box ([x]) = topic written. An unchecked box ([ ]) = topic planned.

Runs in CI alongside build_qa_bank.py.
"""
from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DOCS = REPO_ROOT / "docs"

PHASE_DIR_RE = re.compile(r"^(\d{2})-(.+)$")
# Match both `- [x]` and `- [ ]` items at any indent.
CHECKED_RE = re.compile(r"^\s*- \[x\]", re.MULTILINE | re.IGNORECASE)
UNCHECKED_RE = re.compile(r"^\s*- \[ \]", re.MULTILINE)
# Grab the H1 of each phase index for a nicer display name.
H1_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)


def progress_bar(pct: float, width: int = 20) -> str:
    filled = int(round(pct / 100 * width))
    return "█" * filled + "░" * (width - filled)


def main():
    rows = []
    total_done = 0
    total_all = 0

    for phase_dir in sorted(DOCS.iterdir()):
        if not phase_dir.is_dir():
            continue
        m = PHASE_DIR_RE.match(phase_dir.name)
        if not m:
            continue
        num = int(m.group(1))
        idx = phase_dir / "index.md"
        if not idx.exists():
            continue

        text = idx.read_text()
        done = len(CHECKED_RE.findall(text))
        pending = len(UNCHECKED_RE.findall(text))
        total = done + pending
        pct = (done / total * 100) if total else 0.0

        title_m = H1_RE.search(text)
        if title_m:
            title = title_m.group(1).strip()
            # Strip any "Phase N — " prefix so the phase column stays clean.
            title = re.sub(r"^Phase\s+\d+\s*[—-]\s*", "", title)
        else:
            title = phase_dir.name

        rows.append(
            {
                "num": num,
                "title": title,
                "done": done,
                "total": total,
                "pct": pct,
                "link": f"{phase_dir.name}/index.md",
            }
        )
        total_done += done
        total_all += total

    overall_pct = (total_done / total_all * 100) if total_all else 0.0

    out = [
        "---",
        "tags:",
        "  - progress",
        "---",
        "",
        "# 📊 Progress Dashboard",
        "",
        "> [!NOTE]",
        "> Auto-generated by "
        "[`.github/scripts/build_progress.py`](../.github/scripts/build_progress.py) "
        "from the checkboxes in each phase's `index.md`. "
        "CI regenerates on push to `main`.",
        "",
        "## Overall",
        "",
        f"**{total_done} / {total_all} topics written** — "
        f"**{overall_pct:.0f}%** of the planned curriculum.",
        "",
        f"`{progress_bar(overall_pct, 30)}` {overall_pct:.0f}%",
        "",
        "## Per phase",
        "",
        "| # | Phase | Status | Progress |",
        "|---|---|---|---|",
    ]
    for r in rows:
        status_emoji = "✅" if r["pct"] >= 100 else ("🟡" if r["pct"] > 0 else "📝")
        bar = progress_bar(r["pct"])
        out.append(
            f"| {r['num']} | [{r['title']}]({r['link']}) "
            f"| {status_emoji} {r['done']}/{r['total']} "
            f"| `{bar}` {r['pct']:.0f}% |"
        )

    out.extend([
        "",
        "## Legend",
        "",
        "- ✅ — phase complete",
        "- 🟡 — phase in progress",
        "- 📝 — phase stub (no topics written yet)",
        "",
        "## How to mark a topic as written",
        "",
        "In the phase's `index.md`, flip `- [ ]` to `- [x]` when the topic "
        "file is fully written. CI picks up the change on the next push and "
        "refreshes this dashboard.",
        "",
    ])

    out_path = DOCS / "progress.md"
    out_path.write_text("\n".join(out))
    print(f"Wrote {out_path.relative_to(REPO_ROOT)}")
    print(f"  {total_done}/{total_all} topics ({overall_pct:.0f}%)")


if __name__ == "__main__":
    main()
