#!/usr/bin/env python3
"""Scrape every <details>/<summary> Q&A block across docs/ and regenerate
the interview bank indexes.

Outputs:
  - docs/interview-bank/by-difficulty.md — grouped by easy/medium/hard
  - docs/interview-bank/by-topic.md      — grouped by phase
  - docs/interview-bank/all-questions.md — flat list, for random-study mode

Usage:
  python3 .github/scripts/build_qa_bank.py

Runs in CI (see .github/workflows/regenerate-qa-bank.yml) so contributors
never need to run it locally. Can also be run by hand if you prefer.
"""
from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DOCS = REPO_ROOT / "docs"
BANK = DOCS / "interview-bank"

# Skip these paths (templates, the bank itself — would self-reference).
SKIP_DIRS = {"_templates", "interview-bank"}

# Match frontmatter at the very top of a file.
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
# First-line fields we care about inside frontmatter.
DIFFICULTY_RE = re.compile(r"^difficulty:\s*(\S+)", re.MULTILINE)
STATUS_RE = re.compile(r"^status:\s*(\S+)", re.MULTILINE)
# Tags is a YAML list; grab the whole block then parse lightly.
TAGS_BLOCK_RE = re.compile(r"^tags:\n((?:  - .+\n)+)", re.MULTILINE)
TAG_ITEM_RE = re.compile(r"^  - (.+)$", re.MULTILINE)
# First H1 of the file.
H1_RE = re.compile(r"^# (.+)$", re.MULTILINE)
# Q&A block — match summary content (the question).
QA_BLOCK_RE = re.compile(
    r"<details>\s*<summary>(.*?)</summary>", re.DOTALL
)
# Strip inline markdown/html from summary text for a clean link label.
SUMMARY_CLEANUP_RE = re.compile(r"</?strong>")

PHASE_RE = re.compile(r"^phase-(\d+)$")


@dataclass
class Topic:
    path: Path
    title: str
    difficulty: str  # easy | medium | hard | unknown
    phase: int | None
    tags: list[str] = field(default_factory=list)
    questions: list[str] = field(default_factory=list)

    @property
    def rel_path(self) -> str:
        """Path relative to docs/interview-bank/ (where index files live)."""
        return str(
            Path("..") / self.path.relative_to(DOCS)
        ).replace("\\", "/")


def parse_frontmatter(text: str) -> tuple[str, list[str], str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return "unknown", [], "unknown"
    block = m.group(1)
    diff_m = DIFFICULTY_RE.search(block)
    difficulty = diff_m.group(1).strip() if diff_m else "unknown"
    status_m = STATUS_RE.search(block)
    status = status_m.group(1).strip() if status_m else "unknown"
    tags_m = TAGS_BLOCK_RE.search(block + "\n")  # trailing newline helps regex
    tags = TAG_ITEM_RE.findall(tags_m.group(1)) if tags_m else []
    return difficulty, tags, status


def extract_title(text: str) -> str:
    m = H1_RE.search(text)
    return m.group(1).strip() if m else "(untitled)"


def extract_questions(text: str) -> list[str]:
    qs = []
    for m in QA_BLOCK_RE.finditer(text):
        summary = m.group(1)
        summary = SUMMARY_CLEANUP_RE.sub("", summary)
        summary = summary.strip()
        if summary:
            qs.append(summary)
    return qs


def phase_from_tags(tags: list[str]) -> int | None:
    for t in tags:
        m = PHASE_RE.match(t)
        if m:
            return int(m.group(1))
    return None


def discover_topics() -> list[Topic]:
    topics: list[Topic] = []
    for md in DOCS.rglob("*.md"):
        if any(part in SKIP_DIRS for part in md.relative_to(DOCS).parts):
            continue
        if md.name == "index.md":
            continue  # phase index pages rarely have Q&A
        text = md.read_text()
        questions = extract_questions(text)
        if not questions:
            continue
        difficulty, tags, _status = parse_frontmatter(text)
        title = extract_title(text)
        phase = phase_from_tags(tags)
        topics.append(Topic(md, title, difficulty, phase, tags, questions))
    topics.sort(key=lambda t: (t.phase or 99, t.path.name))
    return topics


# ---- Markdown emission ----------------------------------------------------


HEADER_NOTE = (
    "> [!NOTE]\n"
    "> This index is auto-generated by "
    "[`.github/scripts/build_qa_bank.py`](../../.github/scripts/build_qa_bank.py). "
    "Don't edit by hand — edit the source topic files and CI regenerates this.\n"
)


def q_slug(q: str) -> str:
    """GitHub auto-generates anchors from the <summary> text. Match its rules:
    lowercase, replace non-alphanumeric with hyphen, collapse runs."""
    s = q.lower()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"\s+", "-", s).strip("-")
    return s


def question_link(topic: Topic, q: str) -> str:
    # The anchor GitHub creates from the <summary> content.
    anchor = q_slug(q)
    return f"[{q}]({topic.rel_path}#{anchor})"


def emit_by_difficulty(topics: list[Topic]) -> str:
    buckets: dict[str, list[tuple[Topic, str]]] = defaultdict(list)
    for t in topics:
        for q in t.questions:
            buckets[t.difficulty].append((t, q))

    order = ["easy", "medium", "hard", "unknown"]
    labels = {
        "easy": "🟢 Easy",
        "medium": "🟡 Medium",
        "hard": "🔴 Hard",
        "unknown": "⚪ Unclassified",
    }

    out = [
        "---",
        "tags:",
        "  - interview",
        "---",
        "",
        "# Interview Q&A — By Difficulty",
        "",
        HEADER_NOTE,
        "",
        "Curated by difficulty. Click any question to jump to the full "
        "collapsible Q&A in the source topic.",
        "",
    ]
    total = sum(len(v) for v in buckets.values())
    out.append(f"**Total questions:** {total}")
    out.append("")

    for level in order:
        if not buckets[level]:
            continue
        out.append(f"## {labels[level]}")
        out.append("")
        # Within a level, group by topic for readability.
        by_topic: dict[str, list[tuple[Topic, str]]] = defaultdict(list)
        for topic, q in buckets[level]:
            by_topic[topic.title].append((topic, q))
        for topic_title in sorted(by_topic.keys()):
            entries = by_topic[topic_title]
            out.append(f"### {topic_title}")
            out.append("")
            for topic, q in entries:
                out.append(f"- {question_link(topic, q)}")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def emit_by_topic(topics: list[Topic]) -> str:
    out = [
        "---",
        "tags:",
        "  - interview",
        "---",
        "",
        "# Interview Q&A — By Topic",
        "",
        HEADER_NOTE,
        "",
        "Every topic's questions, grouped by phase.",
        "",
    ]
    total = sum(len(t.questions) for t in topics)
    out.append(f"**Total questions:** {total}")
    out.append("")

    # Group by phase.
    by_phase: dict[int | None, list[Topic]] = defaultdict(list)
    for t in topics:
        by_phase[t.phase].append(t)

    for phase in sorted(by_phase.keys(), key=lambda p: (p is None, p or 0)):
        tlist = by_phase[phase]
        phase_label = f"Phase {phase}" if phase else "Unclassified"
        out.append(f"## {phase_label}")
        out.append("")
        for topic in sorted(tlist, key=lambda t: t.title):
            difficulty = topic.difficulty
            badge = {"easy": "🟢", "medium": "🟡", "hard": "🔴"}.get(
                difficulty, "⚪"
            )
            out.append(
                f"### {badge} [{topic.title}]({topic.rel_path}) "
                f"*({difficulty}, {len(topic.questions)} questions)*"
            )
            out.append("")
            for q in topic.questions:
                out.append(f"- {question_link(topic, q)}")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def emit_all_questions(topics: list[Topic]) -> str:
    out = [
        "---",
        "tags:",
        "  - interview",
        "---",
        "",
        "# All Interview Questions",
        "",
        HEADER_NOTE,
        "",
        "Flat list of every Q&A in the repo. Useful for random-study mode "
        "or ctrl-F across the full corpus.",
        "",
    ]
    n = 0
    for t in sorted(topics, key=lambda x: (x.phase or 99, x.title)):
        for q in t.questions:
            n += 1
            badge = {"easy": "🟢", "medium": "🟡", "hard": "🔴"}.get(
                t.difficulty, "⚪"
            )
            out.append(
                f"{n}. {badge} {question_link(t, q)} "
                f"— *{t.title}*"
            )
    out.append("")
    out.insert(7, f"**Total questions:** {n}")
    out.insert(8, "")
    return "\n".join(out).rstrip() + "\n"


def main():
    topics = discover_topics()
    if not topics:
        print("No topics with Q&A blocks found — nothing to generate.")
        return
    print(f"Scanned {len(topics)} topics with Q&A")

    BANK.mkdir(exist_ok=True)

    (BANK / "by-difficulty.md").write_text(emit_by_difficulty(topics))
    (BANK / "by-topic.md").write_text(emit_by_topic(topics))
    (BANK / "all-questions.md").write_text(emit_all_questions(topics))

    total = sum(len(t.questions) for t in topics)
    print(f"Generated 3 index files covering {total} questions")


if __name__ == "__main__":
    main()
