#!/usr/bin/env python3
"""Scrape frontmatter tags across docs/ and emit docs/tags.md grouped by tag.

Makes cross-phase discovery easy: find every page tagged `distributed-systems`,
`caching`, `solid`, etc. with a single click.
"""
from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DOCS = REPO_ROOT / "docs"

SKIP_DIRS = {"_templates"}

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
TAGS_BLOCK_RE = re.compile(r"^tags:\n((?:  - .+\n)+)", re.MULTILINE)
TAG_ITEM_RE = re.compile(r"^  - (.+)$", re.MULTILINE)
H1_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)

# Tags that describe structure (phase-N, interview) aren't interesting in an
# index page — they'd drown out the topical tags. Filter them out.
STRUCTURAL_TAG_RE = re.compile(r"^(phase-\d+|interview|scenarios|progress)$")


def parse_frontmatter_tags(text: str) -> list[str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return []
    block = m.group(1)
    tm = TAGS_BLOCK_RE.search(block + "\n")
    if not tm:
        return []
    return [t.strip() for t in TAG_ITEM_RE.findall(tm.group(1))]


def extract_title(text: str) -> str:
    m = H1_RE.search(text)
    return m.group(1).strip() if m else "(untitled)"


def rel_from_tags_md(path: Path) -> str:
    return str(path.relative_to(DOCS)).replace("\\", "/")


def main():
    # tag -> list of (title, rel_path)
    tag_pages: dict[str, list[tuple[str, str]]] = defaultdict(list)

    for md in DOCS.rglob("*.md"):
        if any(p in SKIP_DIRS for p in md.relative_to(DOCS).parts):
            continue
        if md.name == "tags.md":
            continue
        text = md.read_text()
        tags = parse_frontmatter_tags(text)
        if not tags:
            continue
        title = extract_title(text)
        rel = rel_from_tags_md(md)
        for t in tags:
            if STRUCTURAL_TAG_RE.match(t):
                continue
            tag_pages[t].append((title, rel))

    out = [
        "---",
        "tags:",
        "  - index",
        "---",
        "",
        "# 🏷️ Tags",
        "",
        "> [!NOTE]",
        "> Auto-generated by "
        "[`.github/scripts/build_tags.py`](../.github/scripts/build_tags.py) "
        "from every topic's frontmatter `tags`. Structural tags "
        "(`phase-N`, `interview`, etc.) are filtered out so topical tags "
        "stand out.",
        "",
        "Tags connect topics across phases. Click any tag header to jump "
        "to its section.",
        "",
        f"**Total tags:** {len(tag_pages)}",
        "",
    ]

    # Table of contents
    out.append("## Index")
    out.append("")
    for tag in sorted(tag_pages.keys()):
        n = len(tag_pages[tag])
        slug = tag.lower().replace(" ", "-")
        out.append(f"- [`{tag}`](#{slug}) — {n} {'page' if n == 1 else 'pages'}")
    out.append("")

    # Sections
    for tag in sorted(tag_pages.keys()):
        pages = tag_pages[tag]
        out.append(f"## `{tag}`")
        out.append("")
        for title, rel in sorted(pages, key=lambda x: x[0].lower()):
            out.append(f"- [{title}]({rel})")
        out.append("")

    out_path = DOCS / "tags.md"
    out_path.write_text("\n".join(out).rstrip() + "\n")
    print(f"Wrote {out_path.relative_to(REPO_ROOT)}")
    print(f"  {len(tag_pages)} tags, "
          f"{sum(len(v) for v in tag_pages.values())} tag references")


if __name__ == "__main__":
    main()
